location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_point_lio_estimator_plugin
    name: mrs_point_lio_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_point_lio_estimator_plugin
    scripts:
      - git submodule update --init --recursive
